### ISSUE TITLE
update fails, with update on the wire

### ISSUE THREAD

**Issue by neopaf** [tarantool/tarantool-idea-plugin#34]
**To Reproduce**
1. Opened test database with pre-created table and record
2. edited record
3. SQL.exception without details

**Expected behavior**
updated record

**Screenshots**

![Снимок экрана 2021-11-12 в 13 10 57](https://user-images.githubusercontent.com/4362564/141449925-411697d5-c0ac-48f7-bd54-079666f1315f.png)
![Снимок экрана 2021-11-12 в 13 11 00](https://user-images.githubusercontent.com/4362564/141449939-44b1a101-bd7f-49ca-b574-31478ba92365.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - DataGrip 2021.2.4
 - Version 0.1.0

**Additional info**

Captured exchange during update, but see no update at all. Just "SELECT 1"

**Comment by neopaf** [comment]
[tarantool-fail.zip](https://github.com/tarantool/tarantool-idea-plugin/files/7526777/tarantool-fail.zip)

**Comment by neopaf** [comment]
idea.log has
```
2021-11-12 13:21:34,067 [  76487]   WARN - ellij.database.util.DbImplUtil - Read-only mode is not supported. Dbms: TARANTOOL 
java.sql.SQLException
	at org.tarantool.jdbc.SQLConnection.setReadOnly(SQLConnection.java:279)
	at com.intellij.database.remote.jdbc.impl.RemoteConnectionImpl.setReadOnly(RemoteConnectionImpl.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by neopaf** [comment]
but this does not correlate with problem time. just some other problem, probably.

**Comment by neopaf** [comment]
![Снимок экрана 2021-11-12 в 13 23 06](https://user-images.githubusercontent.com/4362564/141451521-4dcb6443-5092-4fd9-805b-b51cbbf7f977.png)

**Comment by neopaf** [comment]
![Снимок экрана 2021-11-12 в 13 25 30](https://user-images.githubusercontent.com/4362564/141451886-782331ec-d7b5-4cbd-ba37-5b2b79c25c90.png)

**Comment by neopaf** [comment]
tried both connection modes

**Comment by Periecle** [comment]
Hi, @neopaf. We will investigate your issue. What Tarantool(DB itself) version you are using?

**Comment by neopaf** [comment]
```
[root@tv-vravm081 ~]# tarantool -v
Tarantool 2.8.2-0-gfc96d10
```

my main worry is that there is no update command on the wire during update request from IDE.
and I can't seem to see any details on this obscure sql exception in `idea.log`

I guess, first step is to add those exception details.

maybe I could help debugging this somehow, if I'll attach intellj debugger to datagrip process and try to intercept that exception and try to look into it's message/stacktrace... I'll see

**Comment by neopaf** [comment]
tried but failed. as soon as I attach IDEA to DG the latter hangs (even though it is not paused in IDEA debugger).
not enough experience here :(

**Comment by neopaf** [comment]
![Снимок экрана 2021-11-12 в 15 34 37](https://user-images.githubusercontent.com/4362564/141468182-8d2996b0-6c4e-44b6-bd05-804546cf404c.png)

"submit" on the left is not clickable while debugger on the right is attached :(
